metadata:
  favicon: ''
  title: New module
  description: ''
  breakpoints: []
  rendererCachingEnabled: true
  skipDepsComparisonInCompilerCache: false
  vibeAppConnectedDatasources:
    - '[Sample] Custom App_7ScouI9NPo'
  chatId: '64141'
appSettings:
  properties:
    defaultData: '{}'
  actions: {}
  gridVersion: 2
  density: compact
  hideRenderCachingSettings: false
internalType: vibe_project
id: dqHc4UxvNO
